# Data cleaning for exploring Simpson's paradox

Copyright 2021 Allen B. Downey

License: [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

[Click here to run this notebook on Colab](https://colab.research.google.com/github/AllenDowney/ProbablyOverthinkingIt2/blob/master/simpson_wages.ipynb)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
gss = pd.read_hdf('gss_eda.3.hdf5', 'gss0')
gss.shape

(64814, 169)

In [4]:
recode_polviews = {1:'Liberal', 
                   2:'Liberal', 
                   3:'Liberal', 
                   4:'Moderate', 
                   5:'Conservative', 
                   6:'Conservative', 
                   7:'Conservative'}

In [5]:
gss['polviews3'] = gss['polviews'].replace(recode_polviews)
gss['polviews3'].value_counts()

Moderate        21444
Conservative    19129
Liberal         14979
Name: polviews3, dtype: int64

>Generally speaking, do you usually think of yourself as a Republican, Democrat, Independent, or what?

The valid responses are:

```
0	Strong democrat
1	Not str democrat
2	Ind,near dem
3	Independent
4	Ind,near rep
5	Not str republican
6	Strong republican
7	Other party
```

You can [read the codebook for `partyid` here](https://gssdataexplorer.norc.org/projects/52787/variables/141/vshow).

In [6]:
recode_partyid = {0: 'Democrat',
                  1:'Democrat', 
                   2:'Independent', 
                   3:'Independent', 
                   4:'Independent', 
                   5:'Republican', 
                   6:'Republican', 
                   7:'Other'}

In [7]:
gss['partyid4'] = gss['partyid'].replace(recode_partyid)
gss['partyid4'].value_counts()

Independent    23404
Democrat       23308
Republican     16617
Other           1064
Name: partyid4, dtype: int64

Respondent's highest degree

```
0 	Lt high school
1 	High school
2 	Junior college
3 	Bachelor
4 	Graduate
8 	Don't know
9 	No answer
```



In [8]:
gss['degree'].value_counts()

1.0    33855
0.0    13274
3.0     9277
4.0     4465
2.0     3759
Name: degree, dtype: int64

> What is your religious preference? Is it Protestant, Catholic, Jewish, some other religion, or no religion?

```
1 	Protestant
2 	Catholic
3 	Jewish
4 	None
5 	Other
6 	Buddhism
7 	Hinduism
8 	Other eastern
9 	Moslem/islam
10 	Orthodox-christian
11 	Christian
12 	Native american
13 	Inter-nondenominational
```



In [9]:
recode_relig = {1:'Protestant', 
                   2:'Catholic', 
                   3:'Other', 
                   4:'None', 
                   5:'Other', 
                   6:'Other', 
                   7:'Other', 
                   8:'Other', 
                   9:'Other', 
                   10:'Other Christian', 
                   11:'Other Christian', 
                   12:'Other', 
                   13:'Other'}

In [10]:
gss['relig5'] = gss['relig'].replace(recode_relig)
gss['relig5'].value_counts()

Protestant         36378
Catholic           16501
None                7803
Other               2966
Other Christian      896
Name: relig5, dtype: int64

> If you were asked to use one of four names for your social class, which would you say you belong in: the lower class, the working class, the middle class, or the upper class?
 
```
1 	Lower class
2 	Working class
3 	Middle class
4 	Upper class
5 	No class
8 	Don't know
9 	No answer
0 	Not applicable
```

In [11]:
recode_class = {1:'Lower class', 
                   2:'Working class', 
                   3:'Middle class', 
                   4:'Upper class', 
                   }

In [12]:
gss['class'] = gss['class_'].replace(recode_class)
gss['class'].value_counts()

Working class    28215
Middle class     27746
Lower class       3398
Upper class       1969
Name: class, dtype: int64

```
0 	Lt high school
1 	High school
2 	Junior college
3 	Bachelor
4 	Graduate
```

In [13]:
recode_degree = {0: 'Less than high school',
                  1:'High school', 
                   2:'Junior college', 
                   3:'Bachelor', 
                   4:'Graduate'}

In [14]:
gss['degree5'] = gss['degree'].replace(recode_degree)
gss['degree5'].value_counts()

High school              33855
Less than high school    13274
Bachelor                  9277
Graduate                  4465
Junior college            3759
Name: degree5, dtype: int64

AGE

In [62]:
gss['age'].describe()

count    64633.000000
mean        44.733635
std         17.089962
min         18.000000
25%         30.000000
50%         43.000000
75%         57.000000
max         89.000000
Name: age, dtype: float64

In [63]:
gss['age'].head()

0    60.0
1    53.0
2    72.0
3    19.0
4    44.0
Name: age, dtype: float32

In [65]:
bins = np.arange(17, 95, 5)
print(len(bins))
bins

16


array([17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92])

In [60]:
labels = bins[:-1] + 3

gss['age5'] = pd.cut(gss['age'], bins, labels=labels).astype(float)
gss['age5'].head()

0    60.0
1    55.0
2    70.0
3    20.0
4    45.0
Name: age5, dtype: float64

In [66]:
gss['age5'].value_counts().sort_index()

20.0    5308
25.0    7010
30.0    6776
35.0    6534
40.0    6176
45.0    6103
50.0    5763
55.0    5153
60.0    4457
65.0    3719
70.0    3044
75.0    2155
80.0    1329
85.0     731
90.0     375
Name: age5, dtype: int64

In [67]:
gss['cohort'].head()

0    1912.0
1    1919.0
2    1900.0
3    1953.0
4    1928.0
Name: cohort, dtype: float32

In [68]:
bins = np.arange(1889, 2001, 10)
labels = bins[:-1] + 1

gss['cohort10'] = pd.cut(gss['cohort'], bins, labels=labels).astype(float)
gss['cohort10'].head()

0    1910.0
1    1910.0
2    1900.0
3    1950.0
4    1920.0
Name: cohort10, dtype: float64

In [69]:
gss['cohort10'].value_counts().sort_index()

1890.0      455
1900.0     1717
1910.0     3663
1920.0     5959
1930.0     6889
1940.0    10463
1950.0    13422
1960.0    10123
1970.0     6705
1980.0     3821
1990.0     1345
Name: cohort10, dtype: int64

In [70]:
gss['year'].tail()

64809    2018
64810    2018
64811    2018
64812    2018
64813    2018
Name: year, dtype: int64

In [71]:
bins = np.arange(1970, 2025, 5)
bins

array([1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [72]:
labels = bins[:-1] + 2

gss['year5'] = pd.cut(gss['year'], bins, labels=labels).astype(float)
gss['year5'].tail()

64809    2017.0
64810    2017.0
64811    2017.0
64812    2017.0
64813    2017.0
Name: year5, dtype: float64

In [73]:
gss['year5'].value_counts().sort_index()

1972.0    6091
1977.0    6029
1982.0    6466
1987.0    7679
1992.0    6115
1997.0    8553
2002.0    5577
2007.0    8577
2012.0    4512
2017.0    5215
Name: year5, dtype: int64

Family income on 1972-2006 surveys in constant dollars (base = 1986)

In [74]:
gss['realinc'].describe()

count     57728.000000
mean      34807.546875
std       30804.416016
min         227.000000
25%       14015.000000
50%       26015.000000
75%       44178.750000
max      162607.000000
Name: realinc, dtype: float64

In [75]:
gss['log_realinc'] = np.log10(gss['realinc'])
gss['log_realinc'].describe()

count    57728.000000
mean         4.370259
std          0.433391
min          2.356026
25%          4.146593
50%          4.415224
75%          4.645214
max          5.211139
Name: log_realinc, dtype: float64

In [76]:
temp, bins = pd.qcut(gss['log_realinc'], 10, retbins=True)
temp.head()

0    (4.415, 4.507]
1    (4.329, 4.415]
2    (2.355, 3.829]
3    (4.507, 4.587]
4    (4.587, 4.688]
Name: log_realinc, dtype: category
Categories (10, interval[float64]): [(2.355, 3.829] < (3.829, 4.07] < (4.07, 4.22] < (4.22, 4.329] ... (4.507, 4.587] < (4.587, 4.688] < (4.688, 4.861] < (4.861, 5.211]]

In [77]:
bins

array([2.35602593, 3.82872438, 4.07044411, 4.21950579, 4.32876158,
       4.41522408, 4.50650501, 4.58669996, 4.68833065, 4.86117601,
       5.2111392 ])

In [78]:
labels = np.diff(bins) / 2 + bins[:-1]
labels

array([3.09237516, 3.94958425, 4.14497495, 4.27413368, 4.37199283,
       4.46086454, 4.54660249, 4.63751531, 4.77475333, 5.03615761])

In [81]:
gss['log_realinc10'] = pd.cut(gss['log_realinc'], bins, labels=labels).astype(float)
gss['log_realinc10'].head()

0    4.460865
1    4.371993
2    3.092375
3    4.546602
4    4.637515
Name: log_realinc10, dtype: float64

In [82]:
gss.to_hdf('gss_simpson', 'gss')

/home/downey/anaconda3/envs/ProbablyOverthinkingIt/lib/python3.9/site-packages/pandas/core/generic.py:2606: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block3_values] [items->Index(['polviews3', 'partyid4', 'relig5', 'class', 'degree5'], dtype='object')]

  pytables.to_hdf(
